### ISSUE TITLE
Replace mentions of "OGC APIs"

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-common#336]
There is a request from the OAB for clearer use of terminology regarding OGC API Standards. The idea is to distinguish between a Web API that conforms to an OGC Standard, and the Standards documents themselves.

Please replace all mentions of "OGC APIs" with one of the following, depending on the context:

- "OGC API Standards": Use when referring to the standards themselves
- "implementation of an OGC API Standard": Use when referring to a single product that implements a single OGC API Standard
- "implementation of OGC API Standards": Use when referring to a single product that implements multiple OGC API Standards
- "implementations of an OGC API Standard": Use when referring to multiple products that implement a single OGC API Standard
- "implementations of OGC API Standards": Use when referring to multiple products that implement OGC API Standards
- "suite of OGC API Standards": Use when referring to the family of OGC API Standards

**Comment by cportele** [comment]
The OAB should revisit their guidance.

The stated intent, with which I agree, is:

> The idea is to distinguish between a Web API that conforms to an OGC Standard, and the Standards documents themselves.

But then the guidance is mostly not about Web APIs, but about "products". There is, however, no concept of "product" in OGC API standards. The standardization target is "Web API". The use of "products" seems to be driven by CITE certification considerations, which is still about software products, not the standardization target itself.

Since OGC API standards discuss requirements for Web APIs, not software products that can be used to deploy a Web API, I don't think that OGC API standards should ever refer to "implementations of an OGC API Standard" or something similar.

In OGC API Features we use "[OGC Web API](https://docs.ogc.org/is/17-069r4/17-069r4.html#ogc-webapi)" to refer to Web APIs that implement one or more conformance classes from an OGC API standard.

**Comment by ghobona** [comment]
The text in the guidelines listed above is my interpretation of the OAB's request. I will ask the OAB to post a comment with clarifications .

**Comment by cnreediii** [comment]
Hi. I am the one who wrote a note to the OAB regarding ambiguous, inconsistent, and at times misleading wording WRT to OGC API Standards. Actually, the OAB has not yet discussed. Was supposed to happen last December but was delayed until this month. I need to let Greg know to put the discussion back on the agenda. I am also putting together a much more detailed presentation on incorrect wordings (e.g., an OGC API repository . . .). I have done a fair amount of research on API related terminology and how that terminology is used by companies with major API holdings. 

I am noting ambiguous usages when I review OGC API Standards documents and TB 19 ERs. If only we had looked at common and consistent terminology a couple of years ago! Gobe has quite the task of working to make sure all is consistent now and going forward!

Apologies for any confusion this may have caused. @cportele - WRT In OGC API Features we use "[OGC Web API](https://docs.ogc.org/is/17-069r4/17-069r4.html#ogc-webapi)" to refer to Web APIs that implement one or more conformance classes from an OGC API standard. If I recall correctly, the term was originally introduced in the RFC comment resolution process of Common Part 1. 

Fine - however, this should be clearly stated in each OGC API Standard and not have the reader have to look at Common.  That said, I also think that there is nothing wrong with stating, "Implementations of OGC API - Features . . ." when the context requires such wording. This wording is very clear to the reader as to what is being discussed. 

I will be also ready to discuss in Delft is needed.

**Comment by ghobona** [comment]
All OGC API Standards have now been checked and edits made.
